name: cofrinho_piggy_bank
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.0.1
  flutter_modular: ^0.4.5
  path_provider: ^1.6.0
  hive: ^1.4.0+1
  intl: ^0.16.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.1
  build_runner: ^1.7.4
  hive_generator: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: FredokaOne
      fonts:
         - asset: assets/fonts/FredokaOne-Regular.ttf

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs